### ISSUE TITLE
Get point-cloud from ORB-SLAM2

### ISSUE THREAD

**Issue by shirgo** [AlejandroSilvestri/Osmap-viewer#1]
Hi,
I would like to export the point-cloud only, directly from ORB-SLAM2 or out of the exported map bin file. Is there a simple approach to do that?
Thank you!
Shiran

**Comment by AlejandroSilvestri** [comment]
@shirgo 

So sorry for the late answer.  Today I realized this issue (and many more in other projects) never showed up on my email nor in  my notifications.  I believe you are no longer waiting for this answer, I only telling you osmap doesn't export to any point cloud file format.

_Osmap viewer_ opens an file with osmap format.  You can read _osmap viewer_ code to see how mappoints are extracted from osmap file for visualization.  You also can read _osmap_ code to see how ORB-SLAM2 mappoints info is accessed.

Point cloud doesn't store all data needed for a ORB-SLAM2 map, so it isn't an alternative map file format.  Sadly, Osmap doesn't generate point cloud in any popular file format.  It's up to you to write the exportation code to generate those files.
